site_name: ner-d
site_description: Python module for Named Entity Recognition (NER) using natural language processing.
site_url: https://ner-d.verifid.app/
theme:
  name: material
  palette:
    primary: light-blue
    accent: amber
  favicon: images/favicon.png
  language: en
repo_name: verifid/ner-d
repo_url: https://github.com/verifid/ner-d
edit_uri: ''
nav:
- ner-d: index.md
- installation.md
- Module Documentation:
  - module/ner-d.md
  - module/cli.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - ner-d
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/verifid
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/abdullahselek
  - icon: fontawesome/solid/globe
    link: https://verifid.app
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
